// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-pHT7mhL6LywjchlDh2uAHj_3Dls4VNg',
    appId: '1:379192121648:web:e24ccd887363b673d5d0f5',
    messagingSenderId: '379192121648',
    projectId: 'chat-app-be19a',
    authDomain: 'chat-app-be19a.firebaseapp.com',
    storageBucket: 'chat-app-be19a.appspot.com',
    measurementId: 'G-N2RF1NEC4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Q-SNVzAvFpGY6EKfbO3HzqIcFe6MxXg',
    appId: '1:379192121648:android:a24241224ed443c3d5d0f5',
    messagingSenderId: '379192121648',
    projectId: 'chat-app-be19a',
    storageBucket: 'chat-app-be19a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUHanEqQq-RgLOTfuMEbf8PdWdAoPtdFg',
    appId: '1:379192121648:ios:de7cfaff447debe2d5d0f5',
    messagingSenderId: '379192121648',
    projectId: 'chat-app-be19a',
    storageBucket: 'chat-app-be19a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUHanEqQq-RgLOTfuMEbf8PdWdAoPtdFg',
    appId: '1:379192121648:ios:de7cfaff447debe2d5d0f5',
    messagingSenderId: '379192121648',
    projectId: 'chat-app-be19a',
    storageBucket: 'chat-app-be19a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-pHT7mhL6LywjchlDh2uAHj_3Dls4VNg',
    appId: '1:379192121648:web:8b15ccdad10cec2ed5d0f5',
    messagingSenderId: '379192121648',
    projectId: 'chat-app-be19a',
    authDomain: 'chat-app-be19a.firebaseapp.com',
    storageBucket: 'chat-app-be19a.appspot.com',
    measurementId: 'G-R7108E6XQK',
  );

}